#ifndef __DialogoAsignaturas__
#define __DialogoAsignaturas__

/**
@file
Subclass of GUIDialogoAsignaturas, which is generated by wxFormBuilder.
*/

#include "guidialogoasignaturas.h"

/** Implementing GUIDialogoAsignaturas */
class DialogoAsignaturas : public GUIDialogoAsignaturas
{
public:
	/** Constructor */
	DialogoAsignaturas( wxWindow* parent );
};

#endif // __DialogoAsignaturas__
