#ifndef __DialogoEcaes__
#define __DialogoEcaes__

/**
@file
Subclass of GUIDialogoEcaes, which is generated by wxFormBuilder.
*/

#include "GUIDialogoECAES.h"
#include <vector>
#include <string>

/** Implementing GUIDialogoEcaes */
class DialogoEcaes : public GUIDialogoEcaes
{
public:
	/** Constructor */
	DialogoEcaes( wxWindow* parent );
    std::string getOpciones();
    virtual void botonAceptar( wxCommandEvent& event );
    unsigned int getCantidadComponentes();
    unsigned int getCantidadCompetencias();
    unsigned int getCantidadTotal();
private:
    std::vector<bool> opciones;
    unsigned int cantidad_componentes;
    unsigned int cantidad_competencias;
    unsigned int cantidad_total;
};

#endif // __DialogoEcaes__
