#ifndef __DialogoEcaes__
#define __DialogoEcaes__

/**
@file
Subclass of GUIDialogoEcaes, which is generated by wxFormBuilder.
*/

#include "GUIDialogoECAES.h"

/** Implementing GUIDialogoEcaes */
class DialogoEcaes : public GUIDialogoEcaes
{
public:
	/** Constructor */
	DialogoEcaes( wxWindow* parent );
};

#endif // __DialogoEcaes__
