#ifndef __DialogoAsignaturasMain__
#define __DialogoAsignaturasMain__

/**
@file
Subclass of GUIDialogoAsignaturas, which is generated by wxFormBuilder.
*/

#include "GUIDialogoAsignaturas.h"

/** Implementing GUIDialogoAsignaturas */
class DialogoAsignaturasMain : public GUIDialogoAsignaturas
{
public:
	/** Constructor */
	DialogoAsignaturasMain( wxWindow* parent );
};

#endif // __DialogoAsignaturasMain__
